---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: front-build
          path: build