---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
