---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
      # We don't need separate job for this, because this step generate jobs both for ESlint and Prettier
      - name: Start eslint and prettier
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          eslint_args: "--no-error-on-unmatched-pattern"