---
name: push
on:
  push:
    branches:
      - master
      - dev
    pull_request:
jobs:
  pushImage:
    name: Push docker image
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/toosafinder/${REPO_NAME}
          tag_with_ref: true
