---
name: push
on:
  push:
    branches:
      - master
      - dev
  pull_request:
jobs:
  pushImage:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download npm bundle
        uses: actions/download-artifact@v2
        with:
          name: front-build
          path: build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: docker.pkg.github.com/toosafinder/${{ github.event.repository.name }}