---
name: push
on:
  push:
    branches:
      - master
      - dev
  pull_request:
jobs:
  pushImage:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/toosafinder/${{ github.event.repository.name }}
          tag_with_ref: true
      - name: Download npm bundle
        uses: actions/download-artifact@v2
        with:
          name: front-build