---
name: push
on:
  push:
    branches:
      - master
      - dev
  pull_request:
jobs:
  pushImage:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: toosafinder/${{ github.event.repository.name }}/front
          tag_with_ref: true