apiVersion: v1
kind: Service
metadata:
  name: toosa-frontend-lb
  namespace: prod
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: toosa-frontend-prod
