apiVersion: apps/v1
kind: Deployment
metadata:
  name: toosa-frontend-prod
  namespace: prod
spec:
  selector:
    matchLabels:
      app: toosa-frontend-prod
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: toosa-frontend-prod
    spec:
      containers:
        - image: toosafinder/toosafinder-front:latest
          imagePullPolicy: Always
          name: toosa-frontend-prod
          ports:
            - containerPort: 80
